[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[dev]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"