[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[dev]
  command = "npm run dev -- --host 0.0.0.0 --port 3700"
  publish = "build/"
  functions = "functions/"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"